### ISSUE TITLE
构建本地数据库报错

### ISSUE THREAD

**Issue by lisa4109** [liaoherui/StrainScan#14]
Traceback (most recent call last):
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/bin/strainscan_build", line 10, in <module>
    sys.exit(main())
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/StrainScan/StrainScan_build.py", line 161, in main
    Build_tree.build_tree([cls_res+'/distance_matrix.txt',cls_res+'/hclsMap_95_recls.txt',out_dir+'/Tree_database',31,params])
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/StrainScan/library/Build_tree.py", line 287, in build_tree
    cls_dist, mapping, tree, depths, depths_mapping = hierarchy(fna_mapping, dist)
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/StrainScan/library/Build_tree.py", line 59, in hierarchy
    mapping[i] -= 2
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/bidict/_mut.py", line 78, in __setitem__
    self._put(key, val, self.on_dup)
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/bidict/_base.py", line 219, in _put
    dedup_result = self._dedup_item(key, val, on_dup)
  File "/usr/lishasha/biosoft/miniconda3/envs/strainscan/lib/python3.7/site-packages/bidict/_base.py", line 254, in _dedup_item
    raise KeyAndValueDuplicationError(key, val)
bidict.KeyAndValueDuplicationError: (513, 282)

在构建本地数据库时发生如上报错，总共构建了3个菌，两个菌成功运行，1个失败。成功的两个菌基因组个数在300左右，失败的是600多，是对加入的基因组个数有限制么？

├── Cluster_Result
│   ├── distance_matrix_rebuild.txt
│   ├── distance_matrix.txt
│   ├── hclsMap_95_recls.txt
│   ├── hclsMap_95_Rep.txt
│   ├── hclsMap_95.txt
│   └── Other_Strain_CN.txt
├── Kmer_Sets_L2
└── Tree_database
    ├── nodes_kmer
    ├── overlap
    └── test

报错的1个菌已经生成的文件目录

**Comment by liaoherui** [comment]
Hi, thanks for using StrainScan!

First, may I know the version of your StrainScan? In addition, we'd appreciate it if you could send us the genomes that caused this error. Then, we fix check the program and provide a potential solution asap. Thanks!

**Comment by lisa4109** [comment]
您好，我在软件中没找到命令行查看软件版本，我是用conda 在bioconda通道安装的，安装的时间是2023年9月18号。经过调整测试，我发现不是基因组个数的问题。因为对于之前构建数据库运行成功的基因组，在剔除了一些基因组后，用剩下的基因组构建数据库会存在失败的情况。数据我尝试邮箱发送下到[heruiliao2-c@my.cityu.edu.hk]

**Comment by lisa4109** [comment]
老师，我这边显示邮件发送至heruiliao2-c@my.cityu.edu.hk成功。我的邮箱编号是lishasha@sphsine.com，邮件主题为“heruiliao2-c@my.cityu.edu.hk”，请您查收！

**Comment by lisa4109** [comment]
老师，我这边显示邮件发送至heruiliao2-c@my.cityu.edu.hk成功。我的邮箱编号是lishasha@sphsine.com，邮件主题为“构建本地数据库报错 #14”，请您查收！
